version: '3'

services:
  harvest-mcp:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MCP_PORT=8080
      # The .env file will be copied into the container during build
    restart: unless-stopped
