[project]
name = "harvest-mcp"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "mcp>=1.6.0",
    "python-dotenv>=1.0.0",
]
